ALTER TABLE clients
    ADD COLUMN display_name VARCHAR(300),
    ADD COLUMN dob DATE,
    ADD COLUMN gender VARCHAR(50),
    ADD COLUMN father_spouse_name VARCHAR(300),
    ADD COLUMN alternate_mobile VARCHAR(20),
    ADD COLUMN billing_address TEXT,
    ADD COLUMN id_proof_type VARCHAR(100),
    ADD COLUMN id_proof_number VARCHAR(100),
    ADD COLUMN assigned_advocate VARCHAR(300),
    ADD COLUMN client_since DATE,
    ADD COLUMN referral_source VARCHAR(200),
    ADD COLUMN vakalatnama_on_file BOOLEAN DEFAULT FALSE,
    ADD COLUMN engagement_letter_signed BOOLEAN DEFAULT FALSE,
    ADD COLUMN conflict_notes TEXT,
    ADD COLUMN data_consent BOOLEAN DEFAULT FALSE,
    ADD COLUMN cin VARCHAR(50),
    ADD COLUMN registered_office_address TEXT,
    ADD COLUMN authorized_signatory_name VARCHAR(300),
    ADD COLUMN authorized_signatory_designation VARCHAR(100),
    ADD COLUMN incorporation_date DATE;
